#!/bin/bash
# GitHub Repository Setup Automation
# Automatically creates/connects GitHub repository for deployment

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# PROJECT_ROOT is the current working directory (where the project is)
PROJECT_ROOT="$(pwd)"

echo "🔗 GitHub Repository Setup"
echo ""

# Read config.yaml
if [ ! -f "$PROJECT_ROOT/config.yaml" ]; then
    echo "❌ Error: config.yaml not found in $PROJECT_ROOT"
    exit 1
fi

# Extract project name and git_repo from config.yaml using awk
PROJECT_NAME=$(grep "name:" "$PROJECT_ROOT/config.yaml" | head -1 | awk -F': ' '{print $2}' | tr -d '"' | tr -d ' ')
GIT_REPO=$(grep "git_repo:" "$PROJECT_ROOT/config.yaml" | head -1 | awk -F': ' '{print $2}' | tr -d '"' | tr -d ' ')

echo "   Project directory: $PROJECT_ROOT"
echo "   Project name: $PROJECT_NAME"
echo ""

# Check if Git repo is already initialized and connected
if [ -d "$PROJECT_ROOT/.git" ]; then
    REMOTE_URL=$(cd "$PROJECT_ROOT" && git remote get-url origin 2>/dev/null || echo "")
    if [ -n "$REMOTE_URL" ]; then
        echo "✅ Git repository already connected: $REMOTE_URL"
        echo "   No GitHub setup needed."
        echo ""
        return 0 2>/dev/null || exit 0
    fi
    echo "   Git initialized but no remote. Will create GitHub repo..."
else
    echo "   Git not initialized. Will initialize new repository..."
fi

echo ""

# Check if GitHub CLI (gh) is installed
if ! command -v gh &> /dev/null; then
    echo "📦 GitHub CLI (gh) not found. Attempting to install..."
    
    # Check if Homebrew is available (macOS)
    if command -v brew &> /dev/null; then
        echo "   Installing GitHub CLI via Homebrew..."
        if brew install gh; then
            echo "   ✅ GitHub CLI installed successfully"
        else
            echo "   ❌ Installation failed"
            echo ""
            echo "Please install GitHub CLI manually:"
            echo "  1. Run: brew install gh"
            echo "  2. Authenticate: gh auth login"
            echo "  3. Run this script again"
            exit 1
        fi
    else
        echo "❌ Homebrew not found. Cannot auto-install GitHub CLI."
        echo ""
        echo "Please install GitHub CLI manually:"
        echo "  macOS: brew install gh"
        echo "  Or visit: https://cli.github.com/"
        echo ""
        echo "After installation:"
        echo "  1. Authenticate: gh auth login"
        echo "  2. Run this script again"
        exit 1
    fi
fi

# Check if GitHub CLI is authenticated
echo "🔐 Checking GitHub CLI authentication..."
if ! gh auth status &> /dev/null; then
    echo "   GitHub CLI not authenticated. Please authenticate now."
    echo ""
    gh auth login
    
    # Verify authentication succeeded
    if ! gh auth status &> /dev/null; then
        echo "❌ Authentication failed"
        exit 1
    fi
fi

echo "   ✅ GitHub CLI authenticated"
echo ""

# Initialize Git repository if not already initialized
if [ ! -d "$PROJECT_ROOT/.git" ]; then
    echo "📦 Initializing Git repository..."
    cd "$PROJECT_ROOT"
    
    # Initialize git
    git init
    
    # Create .gitignore if it doesn't exist
    if [ ! -f ".gitignore" ]; then
        echo "   Creating .gitignore..."
        cat > .gitignore << 'EOF'
# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Production build
dist/
build/

# Environment variables
.env
.env.local
.env.production

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Logs
logs/
*.log
npm-debug.log*

# Deployment infrastructure (copied from tool during make deploy)
k8s/
terraform/
docker/Dockerfile.backend
docker/Dockerfile.frontend

# Keep docker-compose.yml for local dev reference
!docker/docker-compose.yml
EOF
        echo "   ✅ .gitignore created"
    fi
    
    # Add all files
    git add -A
    
    # Make initial commit
    git commit -m "Initial commit: $PROJECT_NAME

Generated by Zero-to-Running Developer Environment
Project: $PROJECT_NAME
"
    
    echo "   ✅ Git repository initialized"
    echo "   ✅ Initial commit created"
else
    echo "✅ Git repository already initialized"
    
    # Ensure all current changes are committed before creating GitHub repo
    cd "$PROJECT_ROOT"
    if ! git diff-index --quiet HEAD --; then
        echo "   📝 Uncommitted changes detected. Committing..."
        git add -A
        git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S')

Auto-committed during deployment" || true
    fi
fi

echo ""

# Create GitHub repository
echo "📦 Creating GitHub repository..."
echo "   Repository name: $PROJECT_NAME"
echo ""

# Check if repo already exists on GitHub
if gh repo view "$PROJECT_NAME" &> /dev/null; then
    echo "✅ Repository already exists on GitHub: $PROJECT_NAME"
    REPO_URL=$(gh repo view "$PROJECT_NAME" --json url -q .url)
    
    # Ensure remote is set
    cd "$PROJECT_ROOT"
    if ! git remote get-url origin &> /dev/null; then
        echo "   Setting remote origin..."
        git remote add origin "$REPO_URL" 2>/dev/null || \
        git remote set-url origin "$REPO_URL" 2>/dev/null || true
    fi
    
    # Check if there are unpushed commits (changes were already committed above)
    cd "$PROJECT_ROOT"
    CURRENT_BRANCH=$(git branch --show-current || echo "main")
    HAS_UNPUSHED=$(git rev-list --count origin/$CURRENT_BRANCH..HEAD 2>/dev/null 2>&1 || echo "0")
    
    # Handle case where remote branch doesn't exist yet
    if ! git rev-parse --verify "origin/$CURRENT_BRANCH" &>/dev/null; then
        HAS_UNPUSHED="1"  # Treat as unpushed if branch doesn't exist on remote
    fi
    
    if [ "$HAS_UNPUSHED" != "0" ] && [ "$HAS_UNPUSHED" != "" ]; then
        echo "   📤 Pushing changes to GitHub..."
        git push origin "$CURRENT_BRANCH" 2>/dev/null || \
        git push -u origin "$CURRENT_BRANCH" 2>/dev/null || {
            echo "   ⚠️  Could not push to remote (non-blocking)"
            echo "   You can manually push with: git push origin $CURRENT_BRANCH"
        }
        echo "   ✅ Changes pushed to GitHub"
    else
        echo "   ✅ Repository is up to date (no changes to push)"
    fi
else
    # Create new private repository
    echo "   Creating private repository..."
    gh repo create "$PROJECT_NAME" --private --source=. --remote=origin --push || {
        echo "❌ Failed to create repository"
        echo ""
        echo "Manual steps:"
        echo "  1. Go to https://github.com/new"
        echo "  2. Create repository: $PROJECT_NAME"
        echo "  3. Don't initialize with README"
        echo "  4. Run: git remote add origin <repo-url>"
        echo "  5. Run: git push -u origin main"
        echo "  6. Update config.yaml with repo URL"
        exit 1
    }
    
    REPO_URL=$(gh repo view "$PROJECT_NAME" --json url -q .url)
    echo "   ✅ Repository created: $REPO_URL"
fi

# Update config.yaml with repository URL
echo ""
echo "📝 Updating config.yaml with repository URL..."
if command -v sed &> /dev/null; then
    # macOS/BSD sed requires backup extension
    sed -i.bak "s|git_repo:.*|git_repo: \"$REPO_URL\"|" "$PROJECT_ROOT/config.yaml"
    rm -f "$PROJECT_ROOT/config.yaml.bak"
    echo "   ✅ config.yaml updated"
else
    echo "   ⚠️  Could not auto-update config.yaml"
    echo "   Please manually add: git_repo: \"$REPO_URL\""
fi

echo ""
echo "✅ GitHub setup complete!"
echo "   Repository: $REPO_URL"
echo "   Code pushed to GitHub"
echo ""

